services:
  ansible:
    build:
      context: ./ansible
      dockerfile: Dockerfile
    working_dir: /workspace
    stdin_open: true
    tty: true
    volumes:
      - ./ansible:/workspace
    environment:
      ANSIBLE_CONFIG: /workspace/ansible.cfg
